name: Publish Rust eBooks

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache cargo registry and binaries
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cargo/bin
          key: ${{ runner.os }}-cargo-bin-v1

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y calibre git

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install mdBook (prebuilt)
        uses: peaceiris/actions-mdbook@v2
        with:
          mdbook-version: 'latest'

      - name: Install mdbook-epub (if needed)
        run: |
          if ! command -v mdbook-epub > /dev/null; then
            cargo install mdbook-epub
          fi

      # Build The Rust Book
      - name: Clone The Rust Book source
        run: git clone --depth 1 https://github.com/rust-lang/book.git rust-book

      - name: Enable EPUB backend in book.toml (Rust Book)
        run: echo "[output.epub]" >> rust-book/book.toml

      - name: Build EPUB with mdbook (Rust Book)
        run: cd rust-book && mdbook build

      - name: Copy Rust Book EPUB/AZW3 to site
        run: |
          mkdir -p site
          EPUB_FILE=$(find rust-book/book/epub -name '*.epub' | head -n 1)
          cp "$EPUB_FILE" site/rust-book.epub
          ebook-convert site/rust-book.epub site/rust-book.azw3

      # Build Rust By Example
      - name: Clone Rust By Example source
        run: git clone --depth 1 https://github.com/rust-lang/rust-by-example.git rust-by-example

      - name: Enable EPUB backend in book.toml (Rust By Example)
        run: echo "[output.epub]" >> rust-by-example/book.toml

      - name: Build EPUB with mdbook (Rust By Example)
        run: cd rust-by-example && mdbook build

      - name: Copy Rust By Example EPUB/AZW3 to site
        run: |
          EPUB_FILE=$(find rust-by-example/book/epub -name '*.epub' | head -n 1)
          cp "$EPUB_FILE" site/rust-by-example.epub
          ebook-convert site/rust-by-example.epub site/rust-by-example.azw3

      # Build bookshelf landing page with mdBook
      - name: Update mdBook README with links
        run: |
          cat > mdbook/src/README.md <<EOF
          # Rust Books Nightly eBooks

          Download the latest builds:

          - [The Rust Programming Language (EPUB)](rust-book.epub)
          - [The Rust Programming Language (AZW3)](rust-book.azw3)
          - [Rust By Example (EPUB)](rust-by-example.epub)
          - [Rust By Example (AZW3)](rust-by-example.azw3)
          EOF

      - name: Build mdBook site
        run: cd mdbook && mdbook build

      - name: Prepare site directory
        run: cp -r mdbook/book/* site/

      - name: Upload site artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
